apiVersion: v1
kind: Service
metadata:
  name: cloudpulse-service
  labels:
    app: cloudpulse-ai
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: cloudpulse-ai
